#!/bin/bash -l
#SBATCH --job-name=BRM_Parallelization2
#SBATCH --output=BRM2.o%j
#SBATCH --time=1:00:00
#SBATCH --mem=16G
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mail-type=ALL

module reset
module load R

R --no-save -q < Model_for_small_dataset2.R